### ISSUE TITLE
Landing page wording

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#16]
![image](https://user-images.githubusercontent.com/83494449/117113883-a32a3600-ad7a-11eb-92fd-453106020929.png)
Add 'z' to time.
Change to 'Aircraft Total'
Change to 'Total Fuel Used'
Embolden these and rest of descriptives.

**Comment by PaulB003** [comment]
Change nmi to Nm

**Comment by macofallico** [comment]
Add 'z' to time...... where paul?¿ in the clock

**Comment by macofallico** [comment]
Nm ended placing it by hand is not the best but.... believe it will work just remember that standard Phmvms nautical mile code was overriden or changed in widgets
