### ISSUE TITLE
Dashboard page wording and 'GO' button functionality

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#17]
![image](https://user-images.githubusercontent.com/83494449/117115200-547d9b80-ad7c-11eb-85ff-1c99b44f7319.png)
Change to 'AVG Landing Rate'
Change to 'Submitted' ie delete 'at'
Airport Info 'GO' button disappears after first viewing. To go again, one must select another airport and then reselect the original.

**Comment by macofallico** [comment]
Spelling done, about the buton is a modal buton prevent to be presed and change to the same location only if a new location is selected will apear

**Comment by macofallico** [comment]
Done, if not will reopen
