### ISSUE TITLE
Dashboard page: Info button Weather at XXXX

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#18]
![image](https://user-images.githubusercontent.com/83494449/117118226-0ec2d200-ad80-11eb-8425-926d45acbefc.png)
Change to 'Click here for Weather at XXXX'
Add a note to the right of the opened graphic 'Click on the graphic for full Info'

**Comment by macofallico** [comment]
Done, not a fan in how a note looks but can be done
