### ISSUE TITLE
VA Rules Document

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#19]
Code of conduct etc to be written and posted as Notam.

**Comment by PaulB003** [comment]
Draft sent to Nico

**Comment by PaulB003** [comment]
Document is approved and waiting in Dev Room

**Comment by macofallico** [comment]
Done, closing issue

![image](https://user-images.githubusercontent.com/598859/117347447-83c90100-ae7f-11eb-9d55-00fe56552b18.png)
