### ISSUE TITLE
Wording in Dispatch Flight- Simbrief Page

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#23]
![image](https://user-images.githubusercontent.com/83494449/117221404-b11e9c00-adf8-11eb-9d4a-0c0a7215056b.png)
Change 'ASIGN' to 'ASSIGN' in 'OVERRIDES SIMBRIEF AUTO RUNWAY ASIGN'
Change 'Preferred Flight Level' to 'Select Flight Level'

**Comment by macofallico** [comment]
Done, give me the heads up and i can close it.

**Comment by PaulB003** [comment]
Completed by Maco
