### ISSUE TITLE
Dispatch Page Action Buttons

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#24]
![image](https://user-images.githubusercontent.com/83494449/117223643-9d296900-adfd-11eb-807e-3e99c395df0a.png)
Full Range of buttons please, not just VATSIM, IVAO and Navigraph, as per the Dispatch Flight ¬ Simbrief page

**Comment by macofallico** [comment]
i placed them under weather, because i can add more buttons i can moove them no problem

**Comment by PaulB003** [comment]
Mac and I think that it is fine for now. Just a shame we have to scroll to see them.
