### ISSUE TITLE
New Flight Report Page: add/change wording

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#26]
![image](https://user-images.githubusercontent.com/83494449/117333865-e4107080-ae88-11eb-8923-e9713305d15d.png)
After 'New Flight Report' add '(Proof of Flight may be Required)'
Change 'Level (feet)' to 'Flight Level'
'icon+ FIELDS' appears at the top right of page

**Comment by macofallico** [comment]
Done! Closing
