### ISSUE TITLE
New IVAO Approved Logo to replace existing one ASAP

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#30]
https://cdn.discordapp.com/attachments/812300220389916692/840839000214470656/VA_Logo.zip

**Comment by macofallico** [comment]
![image](https://user-images.githubusercontent.com/598859/118113192-5b2f9280-b3bc-11eb-8f2c-289c1c7a9bf2.png)

**Comment by PaulB003** [comment]
Done by Maco
