### ISSUE TITLE
Flight Details Page: Change Writing form Light Blue to Black (Prefile and Download buttons)

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#31]
![image](https://user-images.githubusercontent.com/83494449/117646686-91320400-b17b-11eb-8883-4a26c3c25ea4.png)

**Comment by macofallico** [comment]
![image](https://user-images.githubusercontent.com/598859/118110857-4f8e9c80-b3b9-11eb-9f39-65ce4fae8074.png)

**Comment by PaulB003** [comment]
Done by Maco
