### ISSUE TITLE
Utils > Zibo Workshop > Forum Thread: Zibo Forum Thread

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#33]
Change Icon as per screenshot (add 'Zibo')
Change Link to https://forums.x-plane.org/index.php?/forums/forum/384-zibo-b738-800-modified/
Link to open in new browser tab
![image](https://user-images.githubusercontent.com/83494449/117648627-fa1a7b80-b17d-11eb-870c-0e5c6140d5a6.png)

**Comment by macofallico** [comment]
![Uploading image.png…]()

**Comment by PaulB003** [comment]
Done by Maco
