### ISSUE TITLE
Utils > Zibo Workshop > Skymatix Page Link: Create New Icon & Link (between Zibo Thread Icon and Zibo Updater Icon)

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#34]
Link is https://forums.x-plane.org/index.php?/forums/topic/185685-zibo-install-guide-training-checklist/
Link to open in new browser tab
Nico & Maco to agree Icon Appearance

**Comment by macofallico** [comment]
provide link an incon and image for the new link placeholder is there

**Comment by PaulB003** [comment]
Created BUT doesn't open in new tab

**Comment by PaulB003** [comment]
Done by Maco
