### ISSUE TITLE
Utils > Zibo Workshop: Header Wording Change & Button Typo

### ISSUE THREAD

**Issue by PaulB003** [macofallico/SkymatixTheme#35]
![image](https://user-images.githubusercontent.com/83494449/117652397-a8c0bb00-b182-11eb-92d1-0e129ae7fc18.png)
Change Header to: 'Zibo Mod B737-800X'
Change 'ZIBO Aproach Notes' to 'ZIBO Approach Notes'

**Comment by macofallico** [comment]
Testsite Fixed

**Comment by PaulB003** [comment]
Done by Maco
