### ISSUE TITLE
Cost Index add V.A. Policy statements

### ISSUE THREAD

**Issue by macofallico** [macofallico/SkymatixTheme#8]
nico´s Job

**Comment by Skymatix** [comment]
Flights less than 2 hours = CI = 20
Flights longer than 2 hours = CI = 40
Flights longer than 4 hours = Pilot's discretion

**Comment by macofallico** [comment]
IF It`s OK i`ll close the enhancement.

![image](https://user-images.githubusercontent.com/598859/116017388-d3a10000-a615-11eb-9477-c40355ca70ef.png)

**Comment by Skymatix** [comment]
Thanks Maco, It seems good to me, you may close this issue
